language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
  -f51e6aed-1097-4116-a636-62b2cdf1b7af

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - shabelnik_ilya@mail.ru
    on_success: never # default: change
    on_failure: always # default: always